#========================================================================
# Copyright 2022 Rodrigo Laiola Guimaraes
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# 
# This program is released under license GNU GPL v3+ license.
#
#========================================================================

version: '3.8'

services:

    # database
    db:
        image: postgres:10
        environment:
            # database configuration
            # privileged user password
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: transaction
        volumes:
            - ./:/src/
        ports:
        - 5032:5032
            

    # Adminer
    adminer:
        image: adminer
        ports:
            - 8080:8080

    # pgAdmin
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=login
            - PGADMIN_DEFAULT_PASSWORD=pass
        ports:
            - 8081:80
